import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
	return (
		<>
			<Head>
				<title>Private Travel Services | Home</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<h1>
				Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo vel
				saepe laboriosam? Asperiores quo ea molestias, non sequi natus nesciunt!
			</h1>
			<h1>
				Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo vel
				saepe laboriosam? Asperiores quo ea molestias, non sequi natus nesciunt!
			</h1>
			<h1>
				Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo vel
				saepe laboriosam? Asperiores quo ea molestias, non sequi natus nesciunt!
			</h1>
			<h1>
				Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo vel
				saepe laboriosam? Asperiores quo ea molestias, non sequi natus nesciunt!
			</h1>
			<h1>
				Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo vel
				saepe laboriosam? Asperiores quo ea molestias, non sequi natus nesciunt!
			</h1>
			<h1>
				Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo vel
				saepe laboriosam? Asperiores quo ea molestias, non sequi natus nesciunt!
			</h1>
			<h1>
				Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo vel
				saepe laboriosam? Asperiores quo ea molestias, non sequi natus nesciunt!
			</h1>
			<h1>
				Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo vel
				saepe laboriosam? Asperiores quo ea molestias, non sequi natus nesciunt!
			</h1>
			<h1>
				Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo vel
				saepe laboriosam? Asperiores quo ea molestias, non sequi natus nesciunt!
			</h1>
			<h1>
				Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo vel
				saepe laboriosam? Asperiores quo ea molestias, non sequi natus nesciunt!
			</h1>
			<h1>
				Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo vel
				saepe laboriosam? Asperiores quo ea molestias, non sequi natus nesciunt!
			</h1>
			<h1>
				Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo vel
				saepe laboriosam? Asperiores quo ea molestias, non sequi natus nesciunt!
			</h1>
			<h1>
				Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo vel
				saepe laboriosam? Asperiores quo ea molestias, non sequi natus nesciunt!
			</h1>
			<h1>
				Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo vel
				saepe laboriosam? Asperiores quo ea molestias, non sequi natus nesciunt!
			</h1>
		</>
	);
}
