import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { TopNavbar } from '../components';

export default function Home() {
	return (
		<>
			<Head>
				<title>Private Travel Services | Home</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
		</>
	);
}
